# Generated by Django 2.2.10 on 2020-02-18 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LightControllerProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField(blank=True, default=None, null=True)),
                ('mode', models.CharField(max_length=50)),
            ],
        ),
    ]
